services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5

  subster-api:
    build:
      context: .
      dockerfile: Subster.API/Dockerfile
    container_name: subster-api
    env_file:
      - .env
    environment:
      # Kestrel listens on 0.0.0.0:${PORT}
      - ASPNETCORE_URLS=http://0.0.0.0:${PORT}
      - ConnectionStrings__SubsterDb=Host=postgres-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      # Map the host port to the container port
      - "${PORT}:${PORT}"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
